
platform :ios, '10.0'
inhibit_all_warnings!

#ali_source 'alibaba-specs'
#ali_source 'alibaba-specs-mirror'

def main_pods

pod 'ZipArchive', '1.4.0'
pod 'CocoaLumberjack', '3.3.0'
pod 'GPUImage', '0.1.7'
pod 'Masonry', '1.0.2'
pod 'UMengAnalytics', '4.2.4'
pod 'Fabric', '1.6.13'
pod 'Crashlytics', '3.8.6'
pod 'AFNetworking', '3.1.0'
pod 'RNCryptor-objc', '3.0.5'
pod 'UMengUShare/UI', '6.4.5'
pod 'UMengUShare/Social/ReducedSina', '6.4.5'
pod 'UMengUShare/Social/ReducedWeChat', '6.4.5'
########################调试##################################
# 注意，发appstore的时候一定要全部移除掉
#pod 'FLEX', '2.1.1-framework'
#pod 'PFEasy', '1.0.1'
#pod 'ATSDK', '0.2.1.56'
#pod 'Reveal-iOS-SDK'
#pod 'dyci'
#pod 'DTFeedbackKit', '0.0.1-SNAPSHOT'
###############################################################
end

target 'OneMinute' do
    platform :ios, '10.0'
    main_pods
end
